declare type Base = "stretch" | "buster" | "bionic" | "disco" | "eoan" | "groovy" | "focal" | "hirsute" | "gitpod/workspace-full";
declare type nodeVersion = "lts" | "current";
export declare class DevcontainerGenerator {
    private base;
    private _dockerfile;
    private _readme;
    private _dockerTemplates;
    private _readmeTemplates;
    private _templateInputs;
    private _nodeVersion;
    private _gitVersion;
    private _cypressVersion;
    private _dotnet;
    private _xfce;
    private _debianBackports;
    private _docker;
    private _android;
    private _vscode;
    private _xpra;
    private _k8s;
    private _deno;
    private _noVNC;
    private _zsh;
    private _chromium;
    private _chrome;
    constructor(base: Base);
    private init;
    setNodeVersion(nodeVersion: nodeVersion): void;
    setVscode(): void;
    updateGit(forceFromSource?: boolean): void;
    setDebianBackports(): void;
    setXfce(): void;
    setDeno(): void;
    setK8s(): void;
    setChrome(): void;
    setChromium(): void;
    setAndroid(): void;
    setRemoteDesktop(type?: "xpra" | "noVNC"): void;
    setZsh(): void;
    setDocker(): void;
    setDotnet(version?: "2" | "3" | "5"): void;
    setCypress(): void;
    generate(): Promise<{
        Dockerfile: string;
        README: string;
    }>;
    private loadTemplate;
}
export {};
